name: Node.js CI

on:
    push:
        branches: [main, pull_request]

jobs:
    build:
        runs-on: [self-hosted, production]

        strategy:
            matrix:
                python-version: ["3.11.2"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install deps
              run: |
                python3 -m pip install --upgrade pip
                if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi

            - name: Restart pm2 process
              run: |
                pm2 status
                pm2 restart outfit
                pm2 status